name = "Greebling"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e41056d86e93c676fa854bafa7439cedfe9d72580074a3bc257f500ac3c523f"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
