name = "Greebling"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd7c62e4ab042fcabfe8d64c9f1c14c1a792a94e1021e49bbda1ecdaa5264d72"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
