name = "Greebling"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bb6de8b0ee1419063ec92cd6fefd266d2b26c2a8d5eea3a4b783b39572ebf2d"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
